### PR TITLE
Update dico.txt

### PR DESCRIPTION
**Pull request by melvinmajor**
dico.txt was a list of 332 terms, now it's a list of 400 terms.

### CODE REVIEW

**Comment by FrancoisDuchene** [comment]
sérieux -_-'

**Comment by FrancoisDuchene** [comment]
tu devrais changer les accents parce que le programme ne les accepte pas encore...

**Comment by melvinmajor** [comment]
dico.txt is now with 405 terms and all accents are now corrected.

**Comment by melvinmajor** [comment]
Now 404 terms (lentilles was 2 times apparently).

**Pull request merged**
